### ISSUE TITLE
openvpn如何和这个系统一起使用

### ISSUE THREAD

**Issue by zgc999** [jasonfish568/vpnadmin#1]

**Comment by zgc999** [comment]
使用client-connect这些？能否放出文件

**Comment by jasonfish568** [comment]
很久没弄过了 michael的那个是不是开始维护了 系统一开始是基于他的配置文件写的 即使使用了radius 异常断开还是会造成流量写入失败 系统本身没什么问题 但是openvpn想做大实在是太麻烦了 最后因为gfw太智能 没有服务器能连上 即使随机端口也很难连上
